name: Build

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      name: Install Current .NET SDK
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:TreatWarningsAsErrors=true
    - name: Run Tests
      run: dotnet test --configuration Release --no-build

